#!/usr/bin/env bash

set -e

USB=/run/media/thederpykrafter/KINGSTON/
SETUP=/home/thederpykrafter/Dev/sh/universal-setup/

test -d "$USB"
test -d "$SETUP"
rsync -rah --progress $SETUP $USB/universal-setup && \
  dunstify -t 10000 -u normal "Universal Setup backup Complete" && \
  echo -e "\e[94mUniversal Setup backup complete!\e[m"
