#!/usr/bin/env bash

PICTURE=/tmp/i3lock.png
SCREENSHOT="scrot -z $PICTURE"
CURSOR="default" # show cursor

BLUR="5x4"

$SCREENSHOT
convert $PICTURE -blur $BLUR $PICTURE

# -e ignores empty password
i3lock -i $PICTURE -p $CURSOR -e -n
rm $PICTURE

# dual monitor fix
sleep 1
i3-msg restart
