#!/usr/bin/env bash

# use nvidia-smi to query gpu temp
# nvidia-smi -q | grep "[0-9] C" | head -n 1 | tr -d ' ' | sed "s/GPUCurrentTemp://" | sed "s/C/°C/"

temp=`nvidia-smi --query-gpu=temperature.gpu --format=csv,noheader`

if (( $temp < 40 )); then
  label=''
elif (( $temp < 50 )); then
  label=''
elif (( $temp < 60 )); then
  label=''
elif (( $temp < 70 )); then
  label=''
else
  label=''
fi

echo $label $temp".0°C"
