#!/usr/bin/env bash

PICTURE=~/.config/i3/i3-lock-screen.png
CURSOR="default" # show cursor

# -e ignores empty password
i3lock -i $PICTURE -p $CURSOR -e -n

# dual monitor fix
sleep 1
i3-msg restart
