#!/usr/bin/env bash

wallpapers=~/.config/i3/EndeavourOS-HD-Wallpaper

wal -i $wallpapers -n -a "0.7" --vte

# sleep 1
for monitor in {1..$((`xrandr --listactivemonitors | wc -l` - 1 ))} ; do
  feh --bg-fill `cat ~/.cache/wal/wal`
done
