#!/usr/bin/env bash

# just in case
polybar-msg cmd quit
killall polybar

# laptop bar
polybar laptop 2>&1 | tee -a /tmp/polybar.log &
disown

# tv bar
[[ $(xrandr | grep "HDMI") ]] && polybar tv 2>&1 | tee -a /tmp/polybar.log &
disown
